- hosts: all
  connection: local
  gather_facts: false
  tasks:
  - name: Query a tenant
    cisco.aci.aci_tenant:
      host: '{{ inventory_hostname }}'
      state: query
      validate_certs: no
   # delegate_to: localhost
    register: query_result
  - name: Display only tenant names
    ansible.builtin.debug:
      var: item
    loop: "{{ community.general.json_query('fvTenant.name') }}"
