---
- name: Create a Tenant, App profile, VRF, Bridge Domain and EPGs
  hosts: all
  gather_facts: false
  connection: local
  vars:
    validate_certs: no
  tasks:
  - name: Create a tenant
    aci_tenant:
      host: '{{ inventory_hostname }}'
      tenant: '{{ aci_tenant }}'
      description: Jambra Ansible i AWX
      state: present
      validate_certs: '{{ validate_certs }}'

  - name: Add a new AP
    aci_ap:
      host: '{{ inventory_hostname }}'
      tenant: '{{ aci_tenant }}'
      ap: '{{ aci_ap_name }}'
      state: present
      validate_certs: '{{ validate_certs }}'

  - name: Add a new VRF to a tenant
    aci_vrf:
      host: '{{ inventory_hostname }}'
      vrf: '{{ aci_vrf }}'
      tenant: '{{ aci_tenant }}'
      policy_control_preference: enforced
      policy_control_direction: ingress
      state: present
      validate_certs: '{{ validate_certs }}'

  - name: Add Bridge Domain
    aci_bd:
      host: '{{ inventory_hostname }}'
      tenant: '{{ aci_tenant }}'
      bd: '{{ aci_bd }}'
      vrf: '{{ aci_vrf }}'
      state: present
      validate_certs: '{{ validate_certs }}'

  - name: Add new EPGs
    aci_epg:
      host: '{{ inventory_hostname }}'
      tenant: '{{ aci_tenant }}'
      ap: '{{ aci_ap_name }}'
      epg: '{{ all_epgs._epg }}'
      description: '{{ all_epgs._desc}}'
      bd: '{{ aci_bd }}'
      priority: unspecified
      intra_epg_isolation: unenforced
      state: present
      validate_certs: '{{ validate_certs }}'
    loop: '{{ aci_epgs }}'
    loop_control:
      loop_var: all_epgs
