---
- name: Create a Tenant, App profile, VRF, Bridge Domain and EPGs
  hosts: all
  gather_facts: false
  connection: local
#  vars:
#    aci_tenant: jambra_ansible_tenant
#    aci_ap_name: jambra_ansible_AP
#    aci_bd: jambra_ansible_BD
#    aci_vrf: jambra_ansible_VRF
#    aci_epgs:
#      - _epg: jambra_ansible_EPG1
#        _desc: EPG1 iz AWX-a
#      - _epg: jambra_ansible_EPG2
#        _desc: EPG2 iz AWX-a 

  tasks:
  - name: Create a tenant
    aci_tenant:
      host: '{{ inventory_hostname }}'
      tenant: '{{ aci_tenant }}'
      description: Jambra Ansible i AWX
      state: present
      validate_certs: no

  - name: Add a new AP
    aci_ap:
      host: '{{ inventory_hostname }}'
      tenant: '{{ aci_tenant }}'
      ap: '{{ aci_ap_name }}'
      description: Jambra Ansible i AWX
      state: present
      validate_certs: no

  - name: Add a new VRF to a tenant
    aci_vrf:
      host: '{{ inventory_hostname }}'
      vrf: '{{ aci_vrf }}'
      tenant: '{{ aci_tenant }}'
      descr: Jambra Ansible i AWX
      policy_control_preference: enforced
      policy_control_direction: ingress
      state: present
      validate_certs: no

  - name: Add Bridge Domain
    aci_bd:
      host: '{{ inventory_hostname }}'
      tenant: '{{ aci_tenant }}'
      bd: '{{ aci_bd }}'
      vrf: '{{ aci_vrf }}'
      state: present
      validate_certs: no

  - name: Add new EPGs
    aci_epg:
      host: '{{ inventory_hostname }}'
      tenant: '{{ aci_tenant }}'
      ap: '{{ aci_ap_name }}'
      epg: '{{ all_epgs._epg }}'
      description: '{{ all_epgs._desc}}'
      bd: '{{ aci_bd }}'
      priority: unspecified
      intra_epg_isolation: unenforced
      state: present
      validate_certs: no
    loop: '{{ aci_epgs }}'
    loop_control:
      loop_var: all_epgs
